name: ci bad
on:
  workflow_dispatch:

env:
  IMAGE_TAGS: ${{ github.sha }}
  IMAGE_REGISTRY: ghcr.io/${{ github.repository_owner }}
  REGISTRY_USER: ${{ github.actor }}
  REGISTRY_PASSWORD: ${{ github.token }}

jobs:
  containerize:
    name: "build container image"
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: download artifact
        uses: actions/download-artifact@v3
        with:
          name: native-executable
          path: target/eventscheduler-1.0.0-SNAPSHOT-native-image-source-jar/
      - name: build image
        uses: redhat-actions/buildah-build@v2
        with:
          base-image: registry.access.redhat.com/ubi8/openjdk-11-runtime
          image: eventscheduler-unsigned
          tags: ${{ env.IMAGE_TAGS }}
          content: |
            target/eventscheduler-1.0.0-SNAPSHOT-native-image-source-jar/eventscheduler-1.0.0-SNAPSHOT-runner.jar
          entrypoint: java -jar scheduler-1.0.0-SNAPSHOT.jar
          port: 8080
      - name: push to registry
        id: push-to-registry
        uses: redhat-actions/push-to-registry@v2
        with:
          image: eventscheduler-unsecured
          tags: ${{ env.IMAGE_TAGS }}
          registry: ${{ env.IMAGE_REGISTRY }}
          username: ${{ env.REGISTRY_USER }}
          password: ${{ env.REGISTRY_PASSWORD }}
          extra-args: |
            --disable-content-trust
    outputs:
      digest: ${{ steps.push-to-registry.outputs.digest }}
    needs: build

  check-image:
    name: check image
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: "Check image"
      uses: ./.github/actions/check-image
      with:
        image: ${{ env.IMAGE_REGISTRY }}/eventscheduler-unsecured@${{ needs.containerize.outputs.digest }}
        central-endpoint: ${{ secrets.ROX_CENTRAL_ENDPOINT }}
        api-token: ${{ secrets.ROX_API_TOKEN }}
    needs: containerize

  #update-deployment-artifacts:

